spring:
  application:
    name: CloudProject
  datasource:
    url: jdbc:postgresql://saidalo-db-30.cdas06uya329.eu-north-1.rds.amazonaws.com:5432/saidalo_db
    username: postgres
    password: b30pdp1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

